### ISSUE TITLE
I am getting exception if I will try to load ifc4 Model in bimserver 1.5.147

### ISSUE THREAD

**Issue by raviarsuda05** [opensourceBIM/GltfSerializers#11]
org.bimserver.plugins.serializers.SerializerException: org.bimserver.plugins.serializers.SerializerException: No geometry
	at org.bimserver.gltf.BinaryGltfSerializer2.write(BinaryGltfSerializer2.java:229)
	at org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:104)
	at org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
	at org.bimserver.plugins.serializers.CacheStoringEmfSerializerDataSource.writeToOutputStream(CacheStoringEmfSerializerDataSource.java:37)
	at org.bimserver.servlets.DownloadServlet.processDataSource(DownloadServlet.java:288)
	at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:249)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:155)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bimserver.plugins.serializers.SerializerException: No geometry
	at org.bimserver.gltf.BinaryGltfSerializer2.generateSceneAndBody(BinaryGltfSerializer2.java:308)
	at org.bimserver.gltf.BinaryGltfSerializer2.write(BinaryGltfSerializer2.java:212)
	... 29 more

**Comment by rubendel** [comment]
Looks like there is no geometry... Any errors while checking in the file? Does it visualize in BIMvie.ws? Can you try the latest release?

**Comment by raviarsuda05** [comment]
no any error while checking. getting error while try to load glb format file

**Comment by raviarsuda05** [comment]
it Does not visualize in BIMvie.ws

**Comment by hlg** [comment]
The schema converter to IFC2x3 does not copy geometry: [AbstractSchemaConverter.java#L58-L60](https://github.com/opensourceBIM/BIMserver/blob/882c52e0781b3370ffeea08611e8d0c00fc72315/BimServer/src/org/bimserver/schemaconverter/AbstractSchemaConverter.java#L58-L60).

One option would be to include geometry in the schema converter, but then, other improvements would be needed as well, such as treating the changes with IfcTypeObject, e.g. IfcDoorStyle replaced by IfcDoorType. It is not clear whether everything can be properly converted and so the geometry and converted IFC might fall out of sync.

As an alternative, the plugin can be changed to cover multiple schema versions, but this must be implemented for every plugin then.
